### PR TITLE
fix: fixed the sortbyRevenue and sortByQuantity using sales

### LINKED ISSUE #59: Fix sales interface
- Make sure that top tipper shows up properly (with tip amount shown)
- Make sure that the items are being sorted properly (by quantity sold and revenue)

### PR DESCRIPTION
**Pull request by Claire-Vu**
## Describe your changes (Include screenshots if neccessary)
-I now have two buttons to sort by revenue and sort by quantity and I implement them by calling the sales methods for them

## Issue ticket number and link
closes #59 
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: csc_335_restaurant/src/view/SalesUI.java [hunk 1]
```diff
@@ -68,7 +71,44 @@ private void initComponents() {
...
+            double revenue = item.getPrice() * item.getQuantity();
+            foodModel.addRow(new Object[]{
+                item.getName(),
+                item.getQuantity(),
+                String.format("%.2f", revenue)
+            });
+        }
+    }
+
+    private void sortByRevenue() {
```
Comment (BaoNguyen09) [inline csc_335_restaurant/src/view/SalesUI.java:93]: A little suggestion: create a boolean to keep track of whether to reverse this sorted list so that user can sort by ascending and descending order

**Review by BaoNguyen09 — APPROVED** [review]

File: csc_335_restaurant/src/view/SalesUI.java (hunk 1 above)
Comment (Claire-Vu) [reply csc_335_restaurant/src/view/SalesUI.java:93]: ok, maybe if we have time later
